Session/4 Mixinの理解
Aosanori/yumemi-flutter-training pull request #17
Opened 2024-04-19 05:53 UTC by Aosanori

## 課題

close #ISSUE_NUMBER

## 対応箇所

- [ ] [AfterBuildStatefulWidgetMixinの導入](https://github.com/Aosanori/yumemi-flutter-training/commit/3353d629ea8b25a587f81cd1ef3d64dd5d609cc7)
- [ ] [LaunchPageStateにAfterBuildStatefulWidgetMixin導入](https://github.com/Aosanori/yumemi-flutter-training/commit/c4affdc33955e3925e3f75db0ee4239b2e3f7988)

2024-04-22 03:48 UTC, Yamasaki-pan961 requested changes
1点コメントしました！

![nits-badge](https://img.shields.io/badge/review-nits-pink.svg)
また、PRの説明にissueがリンクされていないので修正お願いします

2024-04-22 03:48 UTC, Yamasaki-pan961 commented on lib/mixins/after_build_stateful_widget_mixin.dart
> +  Future<void> _redirectToWeatherPageWithWaitingTime(String url) async {
![must-badge](https://img.shields.io/badge/review-must-red.svg)
issueの仕様と少し違う実装になっているようです。修正お願いします！

- #5 
> レイアウトが表示された後に「何かしらの処理」を行う [Mixin](https://dart.dev/guides/language/language-tour#adding-features-to-a-class-mixins) を作成する
作成した [Mixin](https://dart.dev/guides/language/language-tour#adding-features-to-a-class-mixins) の使用先で「何かしらの処理」を記述できるようにする

2024-04-23 01:05 UTC, Aosanori commented on lib/mixins/after_build_stateful_widget_mixin.dart
> +  Future<void> _redirectToWeatherPageWithWaitingTime(String url) async {
[🐛 仕様の通りにレイアウトが表示された後に「何かしらの処理」を行う Mixin を作成](https://github.com/Aosanori/yumemi-flutter-training/pull/17/commits/94753afec4afe8c68952ecbb3ad1ef4a8de3815a) にて修正しました！

2024-04-23 01:07 UTC, Yamasaki-pan961 commented on lib/mixins/after_build_stateful_widget_mixin.dart
> +  void afterFirstBuild() {}
![must-badge](https://img.shields.io/badge/review-must-red.svg)
ここは抽象メソッドで定義するとmixin使用側でオーバーライドを矯正できて安全になります！

2024-04-23 01:13 UTC, Aosanori commented on lib/mixins/after_build_stateful_widget_mixin.dart
> +  void afterFirstBuild() {}
抽象メソッド初めて知りました！継承先で必ず呼び出させるよう強制できるのはすごいですね！
[♻️ AfterFirstBuildを抽象メソッドに](https://github.com/Aosanori/yumemi-flutter-training/pull/17/commits/bfdfd9152f9540531ab7c9e715ece1887f34691a)にて修正しました！

2024-04-23 05:14 UTC, Yamasaki-pan961 commented on lib/mixins/after_build_stateful_widget_mixin.dart
> +  void afterFirstBuild() {}
修正ありがとうございます！

細かい話で申し訳ないんですが、、
> 継承先で必ず呼び出させるよう強制できる
以上の文は話の流れで伝わるのですが、　正確には「実装を強制させる」ですね。
「呼び出しの強制」と言ってしまうと語弊が生まれるかもしれません！

2024-04-23 05:24 UTC, Yamasaki-pan961 approved these changes
![LGTM](https://image.lgtmoon.dev/244979)

2024-04-23 05:38 UTC, merged